/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as SessionRouteImport } from './routes/_session'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PronunciationRouteImport } from './routes/_pronunciation'
import { Route as LoginRouteImport } from './routes/_login'
import { Route as LessonRouteImport } from './routes/_lesson'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as ConversationRouteImport } from './routes/_conversation'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicTermsRouteImport } from './routes/_public.terms'
import { Route as PublicRefundRouteImport } from './routes/_public.refund'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicPricingRouteImport } from './routes/_public.pricing'
import { Route as PublicFeaturesRouteImport } from './routes/_public.features'
import { Route as PublicBlogRouteImport } from './routes/_public.blog'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as LoginVerifyRouteImport } from './routes/_login.verify'
import { Route as LoginSignupRouteImport } from './routes/_login.signup'
import { Route as LoginResetPasswordRouteImport } from './routes/_login.reset-password'
import { Route as LoginLoginRouteImport } from './routes/_login.login'
import { Route as LoginForgotPasswordRouteImport } from './routes/_login.forgot-password'
import { Route as DashboardVocabularyRouteImport } from './routes/_dashboard.vocabulary'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardPracticeRouteImport } from './routes/_dashboard.practice'
import { Route as DashboardLessonsRouteImport } from './routes/_dashboard.lessons'
import { Route as DashboardHomeRouteImport } from './routes/_dashboard.home'
import { Route as DashboardGrammarRouteImport } from './routes/_dashboard.grammar'
import { Route as DashboardFluencyRouteImport } from './routes/_dashboard.fluency'
import { Route as DashboardCoursesRouteImport } from './routes/_dashboard.courses'
import { Route as SessionSessionIndexRouteImport } from './routes/_session.session.index'
import { Route as PronunciationPronunciationIndexRouteImport } from './routes/_pronunciation.pronunciation.index'
import { Route as DashboardCoursesIndexRouteImport } from './routes/_dashboard.courses.index'
import { Route as ConversationConversationIndexRouteImport } from './routes/_conversation.conversation.index'
import { Route as SessionSessionSessionIdRouteImport } from './routes/_session.session.$sessionId'
import { Route as SessionFeedbackSessionIdRouteImport } from './routes/_session.feedback.$sessionId'
import { Route as PronunciationPronunciationSessionIdRouteImport } from './routes/_pronunciation.pronunciation.$sessionId'
import { Route as LessonLessonLessonIdRouteImport } from './routes/_lesson.lesson.$lessonId'
import { Route as DashboardCoursesCourseIdRouteImport } from './routes/_dashboard.courses.$courseId'
import { Route as ConversationConversationSessionIdRouteImport } from './routes/_conversation.conversation.$sessionId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/_session',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationRoute = PronunciationRouteImport.update({
  id: '/_pronunciation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/_login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonRoute = LessonRouteImport.update({
  id: '/_lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/_conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRefundRoute = PublicRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFeaturesRoute = PublicFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogRoute = PublicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const LoginVerifyRoute = LoginVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => LoginRoute,
} as any)
const LoginSignupRoute = LoginSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LoginRoute,
} as any)
const LoginResetPasswordRoute = LoginResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LoginRoute,
} as any)
const LoginLoginRoute = LoginLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LoginRoute,
} as any)
const LoginForgotPasswordRoute = LoginForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LoginRoute,
} as any)
const DashboardVocabularyRoute = DashboardVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPracticeRoute = DashboardPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLessonsRoute = DashboardLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGrammarRoute = DashboardGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFluencyRoute = DashboardFluencyRouteImport.update({
  id: '/fluency',
  path: '/fluency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const SessionSessionIndexRoute = SessionSessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => SessionRoute,
} as any)
const PronunciationPronunciationIndexRoute =
  PronunciationPronunciationIndexRouteImport.update({
    id: '/pronunciation/',
    path: '/pronunciation/',
    getParentRoute: () => PronunciationRoute,
  } as any)
const DashboardCoursesIndexRoute = DashboardCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCoursesRoute,
} as any)
const ConversationConversationIndexRoute =
  ConversationConversationIndexRouteImport.update({
    id: '/conversation/',
    path: '/conversation/',
    getParentRoute: () => ConversationRoute,
  } as any)
const SessionSessionSessionIdRoute = SessionSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => SessionRoute,
} as any)
const SessionFeedbackSessionIdRoute =
  SessionFeedbackSessionIdRouteImport.update({
    id: '/feedback/$sessionId',
    path: '/feedback/$sessionId',
    getParentRoute: () => SessionRoute,
  } as any)
const PronunciationPronunciationSessionIdRoute =
  PronunciationPronunciationSessionIdRouteImport.update({
    id: '/pronunciation/$sessionId',
    path: '/pronunciation/$sessionId',
    getParentRoute: () => PronunciationRoute,
  } as any)
const LessonLessonLessonIdRoute = LessonLessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => LessonRoute,
} as any)
const DashboardCoursesCourseIdRoute =
  DashboardCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)
const ConversationConversationSessionIdRoute =
  ConversationConversationSessionIdRouteImport.update({
    id: '/conversation/$sessionId',
    path: '/conversation/$sessionId',
    getParentRoute: () => ConversationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/courses': typeof DashboardCoursesRouteWithChildren
  '/fluency': typeof DashboardFluencyRoute
  '/grammar': typeof DashboardGrammarRoute
  '/home': typeof DashboardHomeRoute
  '/lessons': typeof DashboardLessonsRoute
  '/practice': typeof DashboardPracticeRoute
  '/settings': typeof DashboardSettingsRoute
  '/vocabulary': typeof DashboardVocabularyRoute
  '/forgot-password': typeof LoginForgotPasswordRoute
  '/login': typeof LoginLoginRoute
  '/reset-password': typeof LoginResetPasswordRoute
  '/signup': typeof LoginSignupRoute
  '/verify': typeof LoginVerifyRoute
  '/about': typeof PublicAboutRoute
  '/blog': typeof PublicBlogRoute
  '/features': typeof PublicFeaturesRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/refund': typeof PublicRefundRoute
  '/terms': typeof PublicTermsRoute
  '/': typeof PublicIndexRoute
  '/conversation/$sessionId': typeof ConversationConversationSessionIdRoute
  '/courses/$courseId': typeof DashboardCoursesCourseIdRoute
  '/lesson/$lessonId': typeof LessonLessonLessonIdRoute
  '/pronunciation/$sessionId': typeof PronunciationPronunciationSessionIdRoute
  '/feedback/$sessionId': typeof SessionFeedbackSessionIdRoute
  '/session/$sessionId': typeof SessionSessionSessionIdRoute
  '/conversation': typeof ConversationConversationIndexRoute
  '/courses/': typeof DashboardCoursesIndexRoute
  '/pronunciation': typeof PronunciationPronunciationIndexRoute
  '/session': typeof SessionSessionIndexRoute
}
export interface FileRoutesByTo {
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/fluency': typeof DashboardFluencyRoute
  '/grammar': typeof DashboardGrammarRoute
  '/home': typeof DashboardHomeRoute
  '/lessons': typeof DashboardLessonsRoute
  '/practice': typeof DashboardPracticeRoute
  '/settings': typeof DashboardSettingsRoute
  '/vocabulary': typeof DashboardVocabularyRoute
  '/forgot-password': typeof LoginForgotPasswordRoute
  '/login': typeof LoginLoginRoute
  '/reset-password': typeof LoginResetPasswordRoute
  '/signup': typeof LoginSignupRoute
  '/verify': typeof LoginVerifyRoute
  '/about': typeof PublicAboutRoute
  '/blog': typeof PublicBlogRoute
  '/features': typeof PublicFeaturesRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/refund': typeof PublicRefundRoute
  '/terms': typeof PublicTermsRoute
  '/': typeof PublicIndexRoute
  '/conversation/$sessionId': typeof ConversationConversationSessionIdRoute
  '/courses/$courseId': typeof DashboardCoursesCourseIdRoute
  '/lesson/$lessonId': typeof LessonLessonLessonIdRoute
  '/pronunciation/$sessionId': typeof PronunciationPronunciationSessionIdRoute
  '/feedback/$sessionId': typeof SessionFeedbackSessionIdRoute
  '/session/$sessionId': typeof SessionSessionSessionIdRoute
  '/conversation': typeof ConversationConversationIndexRoute
  '/courses': typeof DashboardCoursesIndexRoute
  '/pronunciation': typeof PronunciationPronunciationIndexRoute
  '/session': typeof SessionSessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_conversation': typeof ConversationRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_lesson': typeof LessonRouteWithChildren
  '/_login': typeof LoginRouteWithChildren
  '/_pronunciation': typeof PronunciationRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_session': typeof SessionRouteWithChildren
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/_dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/_dashboard/fluency': typeof DashboardFluencyRoute
  '/_dashboard/grammar': typeof DashboardGrammarRoute
  '/_dashboard/home': typeof DashboardHomeRoute
  '/_dashboard/lessons': typeof DashboardLessonsRoute
  '/_dashboard/practice': typeof DashboardPracticeRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/vocabulary': typeof DashboardVocabularyRoute
  '/_login/forgot-password': typeof LoginForgotPasswordRoute
  '/_login/login': typeof LoginLoginRoute
  '/_login/reset-password': typeof LoginResetPasswordRoute
  '/_login/signup': typeof LoginSignupRoute
  '/_login/verify': typeof LoginVerifyRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/blog': typeof PublicBlogRoute
  '/_public/features': typeof PublicFeaturesRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/refund': typeof PublicRefundRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_conversation/conversation/$sessionId': typeof ConversationConversationSessionIdRoute
  '/_dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRoute
  '/_lesson/lesson/$lessonId': typeof LessonLessonLessonIdRoute
  '/_pronunciation/pronunciation/$sessionId': typeof PronunciationPronunciationSessionIdRoute
  '/_session/feedback/$sessionId': typeof SessionFeedbackSessionIdRoute
  '/_session/session/$sessionId': typeof SessionSessionSessionIdRoute
  '/_conversation/conversation/': typeof ConversationConversationIndexRoute
  '/_dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/_pronunciation/pronunciation/': typeof PronunciationPronunciationIndexRoute
  '/_session/session/': typeof SessionSessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/generating'
    | '/onboarding'
    | '/courses'
    | '/fluency'
    | '/grammar'
    | '/home'
    | '/lessons'
    | '/practice'
    | '/settings'
    | '/vocabulary'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/about'
    | '/blog'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/'
    | '/conversation/$sessionId'
    | '/courses/$courseId'
    | '/lesson/$lessonId'
    | '/pronunciation/$sessionId'
    | '/feedback/$sessionId'
    | '/session/$sessionId'
    | '/conversation'
    | '/courses/'
    | '/pronunciation'
    | '/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/generating'
    | '/onboarding'
    | '/fluency'
    | '/grammar'
    | '/home'
    | '/lessons'
    | '/practice'
    | '/settings'
    | '/vocabulary'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/about'
    | '/blog'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/'
    | '/conversation/$sessionId'
    | '/courses/$courseId'
    | '/lesson/$lessonId'
    | '/pronunciation/$sessionId'
    | '/feedback/$sessionId'
    | '/session/$sessionId'
    | '/conversation'
    | '/courses'
    | '/pronunciation'
    | '/session'
  id:
    | '__root__'
    | '/_conversation'
    | '/_dashboard'
    | '/_lesson'
    | '/_login'
    | '/_pronunciation'
    | '/_public'
    | '/_session'
    | '/generating'
    | '/onboarding'
    | '/_dashboard/courses'
    | '/_dashboard/fluency'
    | '/_dashboard/grammar'
    | '/_dashboard/home'
    | '/_dashboard/lessons'
    | '/_dashboard/practice'
    | '/_dashboard/settings'
    | '/_dashboard/vocabulary'
    | '/_login/forgot-password'
    | '/_login/login'
    | '/_login/reset-password'
    | '/_login/signup'
    | '/_login/verify'
    | '/_public/about'
    | '/_public/blog'
    | '/_public/features'
    | '/_public/pricing'
    | '/_public/privacy'
    | '/_public/refund'
    | '/_public/terms'
    | '/_public/'
    | '/_conversation/conversation/$sessionId'
    | '/_dashboard/courses/$courseId'
    | '/_lesson/lesson/$lessonId'
    | '/_pronunciation/pronunciation/$sessionId'
    | '/_session/feedback/$sessionId'
    | '/_session/session/$sessionId'
    | '/_conversation/conversation/'
    | '/_dashboard/courses/'
    | '/_pronunciation/pronunciation/'
    | '/_session/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConversationRoute: typeof ConversationRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LessonRoute: typeof LessonRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  PronunciationRoute: typeof PronunciationRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  SessionRoute: typeof SessionRouteWithChildren
  GeneratingRoute: typeof GeneratingRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_session': {
      id: '/_session'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pronunciation': {
      id: '/_pronunciation'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PronunciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login': {
      id: '/_login'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lesson': {
      id: '/_lesson'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_conversation': {
      id: '/_conversation'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/refund': {
      id: '/_public/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof PublicRefundRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/features': {
      id: '/_public/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof PublicFeaturesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_login/verify': {
      id: '/_login/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof LoginVerifyRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_login/signup': {
      id: '/_login/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LoginSignupRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_login/reset-password': {
      id: '/_login/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof LoginResetPasswordRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_login/login': {
      id: '/_login/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLoginRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_login/forgot-password': {
      id: '/_login/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof LoginForgotPasswordRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_dashboard/vocabulary': {
      id: '/_dashboard/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof DashboardVocabularyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/practice': {
      id: '/_dashboard/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof DashboardPracticeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/lessons': {
      id: '/_dashboard/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof DashboardLessonsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/home': {
      id: '/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/grammar': {
      id: '/_dashboard/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof DashboardGrammarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fluency': {
      id: '/_dashboard/fluency'
      path: '/fluency'
      fullPath: '/fluency'
      preLoaderRoute: typeof DashboardFluencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/courses': {
      id: '/_dashboard/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_session/session/': {
      id: '/_session/session/'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionSessionIndexRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_pronunciation/pronunciation/': {
      id: '/_pronunciation/pronunciation/'
      path: '/pronunciation'
      fullPath: '/pronunciation'
      preLoaderRoute: typeof PronunciationPronunciationIndexRouteImport
      parentRoute: typeof PronunciationRoute
    }
    '/_dashboard/courses/': {
      id: '/_dashboard/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof DashboardCoursesIndexRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/_conversation/conversation/': {
      id: '/_conversation/conversation/'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationConversationIndexRouteImport
      parentRoute: typeof ConversationRoute
    }
    '/_session/session/$sessionId': {
      id: '/_session/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionSessionIdRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_session/feedback/$sessionId': {
      id: '/_session/feedback/$sessionId'
      path: '/feedback/$sessionId'
      fullPath: '/feedback/$sessionId'
      preLoaderRoute: typeof SessionFeedbackSessionIdRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_pronunciation/pronunciation/$sessionId': {
      id: '/_pronunciation/pronunciation/$sessionId'
      path: '/pronunciation/$sessionId'
      fullPath: '/pronunciation/$sessionId'
      preLoaderRoute: typeof PronunciationPronunciationSessionIdRouteImport
      parentRoute: typeof PronunciationRoute
    }
    '/_lesson/lesson/$lessonId': {
      id: '/_lesson/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonLessonIdRouteImport
      parentRoute: typeof LessonRoute
    }
    '/_dashboard/courses/$courseId': {
      id: '/_dashboard/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof DashboardCoursesCourseIdRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/_conversation/conversation/$sessionId': {
      id: '/_conversation/conversation/$sessionId'
      path: '/conversation/$sessionId'
      fullPath: '/conversation/$sessionId'
      preLoaderRoute: typeof ConversationConversationSessionIdRouteImport
      parentRoute: typeof ConversationRoute
    }
  }
}

interface ConversationRouteChildren {
  ConversationConversationSessionIdRoute: typeof ConversationConversationSessionIdRoute
  ConversationConversationIndexRoute: typeof ConversationConversationIndexRoute
}

const ConversationRouteChildren: ConversationRouteChildren = {
  ConversationConversationSessionIdRoute:
    ConversationConversationSessionIdRoute,
  ConversationConversationIndexRoute: ConversationConversationIndexRoute,
}

const ConversationRouteWithChildren = ConversationRoute._addFileChildren(
  ConversationRouteChildren,
)

interface DashboardCoursesRouteChildren {
  DashboardCoursesCourseIdRoute: typeof DashboardCoursesCourseIdRoute
  DashboardCoursesIndexRoute: typeof DashboardCoursesIndexRoute
}

const DashboardCoursesRouteChildren: DashboardCoursesRouteChildren = {
  DashboardCoursesCourseIdRoute: DashboardCoursesCourseIdRoute,
  DashboardCoursesIndexRoute: DashboardCoursesIndexRoute,
}

const DashboardCoursesRouteWithChildren =
  DashboardCoursesRoute._addFileChildren(DashboardCoursesRouteChildren)

interface DashboardRouteChildren {
  DashboardCoursesRoute: typeof DashboardCoursesRouteWithChildren
  DashboardFluencyRoute: typeof DashboardFluencyRoute
  DashboardGrammarRoute: typeof DashboardGrammarRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardLessonsRoute: typeof DashboardLessonsRoute
  DashboardPracticeRoute: typeof DashboardPracticeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVocabularyRoute: typeof DashboardVocabularyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCoursesRoute: DashboardCoursesRouteWithChildren,
  DashboardFluencyRoute: DashboardFluencyRoute,
  DashboardGrammarRoute: DashboardGrammarRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardLessonsRoute: DashboardLessonsRoute,
  DashboardPracticeRoute: DashboardPracticeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVocabularyRoute: DashboardVocabularyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LessonRouteChildren {
  LessonLessonLessonIdRoute: typeof LessonLessonLessonIdRoute
}

const LessonRouteChildren: LessonRouteChildren = {
  LessonLessonLessonIdRoute: LessonLessonLessonIdRoute,
}

const LessonRouteWithChildren =
  LessonRoute._addFileChildren(LessonRouteChildren)

interface LoginRouteChildren {
  LoginForgotPasswordRoute: typeof LoginForgotPasswordRoute
  LoginLoginRoute: typeof LoginLoginRoute
  LoginResetPasswordRoute: typeof LoginResetPasswordRoute
  LoginSignupRoute: typeof LoginSignupRoute
  LoginVerifyRoute: typeof LoginVerifyRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginForgotPasswordRoute: LoginForgotPasswordRoute,
  LoginLoginRoute: LoginLoginRoute,
  LoginResetPasswordRoute: LoginResetPasswordRoute,
  LoginSignupRoute: LoginSignupRoute,
  LoginVerifyRoute: LoginVerifyRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface PronunciationRouteChildren {
  PronunciationPronunciationSessionIdRoute: typeof PronunciationPronunciationSessionIdRoute
  PronunciationPronunciationIndexRoute: typeof PronunciationPronunciationIndexRoute
}

const PronunciationRouteChildren: PronunciationRouteChildren = {
  PronunciationPronunciationSessionIdRoute:
    PronunciationPronunciationSessionIdRoute,
  PronunciationPronunciationIndexRoute: PronunciationPronunciationIndexRoute,
}

const PronunciationRouteWithChildren = PronunciationRoute._addFileChildren(
  PronunciationRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicBlogRoute: typeof PublicBlogRoute
  PublicFeaturesRoute: typeof PublicFeaturesRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicRefundRoute: typeof PublicRefundRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicBlogRoute: PublicBlogRoute,
  PublicFeaturesRoute: PublicFeaturesRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicRefundRoute: PublicRefundRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface SessionRouteChildren {
  SessionFeedbackSessionIdRoute: typeof SessionFeedbackSessionIdRoute
  SessionSessionSessionIdRoute: typeof SessionSessionSessionIdRoute
  SessionSessionIndexRoute: typeof SessionSessionIndexRoute
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionFeedbackSessionIdRoute: SessionFeedbackSessionIdRoute,
  SessionSessionSessionIdRoute: SessionSessionSessionIdRoute,
  SessionSessionIndexRoute: SessionSessionIndexRoute,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConversationRoute: ConversationRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LessonRoute: LessonRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  PronunciationRoute: PronunciationRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  SessionRoute: SessionRouteWithChildren,
  GeneratingRoute: GeneratingRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
