export const FREE_LESSON_FREE_UNIT_COUNT = 1;
export const FREE_DAILY_NEW_LESSON_STARTS = 1;

export const FREE_DAILY_CONVERSATIONS = 1;
export const FREE_CONVERSATION_MAX_AI_REPLIES = 8;

export const FREE_DAILY_PRONUNCIATION_SESSIONS = 1;
export const FREE_PRONUNCIATION_MAX_ATTEMPTS = 3;

export const FREE_DAILY_VOCAB_REVIEW_LIMIT = 15;
export const FREE_DAILY_VOCAB_ADDS_LIMIT = 10;

export const FREE_CONVERSATION_PREVIEW_CORRECTIONS = 2;
